//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroccoliTrade.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccreditationSupplements
    {
        public string id { get; set; }
        public string Number { get; set; }
        public string Command { get; set; }
        public string Accreditationfk { get; set; }
    }
}
