//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroccoliTrade.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BroccoliEntities : DbContext
    {
        public BroccoliEntities()
            : base("name=BroccoliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Users> Users { get; set; }
        public DbSet<Accounts> Accounts { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<AccountPool> AccountPool { get; set; }
        public DbSet<Systems> Systems { get; set; }
        public DbSet<TradingSystemPool> TradingSystemPool { get; set; }
        public DbSet<TradingSystems> TradingSystems { get; set; }
        public DbSet<AccreditationProgram> AccreditationProgram { get; set; }
        public DbSet<AccreditationSupplements> AccreditationSupplements { get; set; }
    }
}
