//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroccoliTrade.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mails
    {
        public int Id { get; set; }
        public int MailNumber { get; set; }
        public string MailName { get; set; }
        public string MailBody { get; set; }
        public int GroupId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual UserGroups UserGroups { get; set; }
    }
}
