//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroccoliTrade.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referrer
    {
        public int Id { get; set; }
        public string Host { get; set; }
        public int Count { get; set; }
        public long OwnerId { get; set; }
        public bool IsDeleted { get; set; }
        public int RegisteredCount { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
