//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroccoliTrade.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingSystemPool
    {
        public int Id { get; set; }
        public long UserId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public int AccountId { get; set; }
        public int TradingSystemId { get; set; }
        public bool ByInvite { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Users Users { get; set; }
        public virtual TradingSystems TradingSystems { get; set; }
    }
}
