//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroccoliTrade.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingSystems
    {
        public TradingSystems()
        {
            this.TradingSystemPool = new HashSet<TradingSystemPool>();
        }
    
        public int Id { get; set; }
        public int SystemId { get; set; }
        public long UserId { get; set; }
        public int StatusId { get; set; }
        public int AccountId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Status Status { get; set; }
        public virtual Systems Systems { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<TradingSystemPool> TradingSystemPool { get; set; }
    }
}
