//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroccoliTrade.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Body { get; set; }
        public bool IsConfirmed { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
        public long UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
